---
extends:
  - prettier
  - concierge-auctions-react
plugins:
  - prettier
rules:
  arrow-parens: "off"
  prettier/prettier:
    - error
  react/require-default-props: "off"
  jsx-a11y/img-has-alt: "off"
  space-before-function-paren:
    - error
    - anonymous: "always"
      named: "never"
      asyncArrow: "always"
  no-underscore-dangle:
    - error
    - allowAfterThis: true
      allow:
        - _handleNestedListToggle
        - _disableDisplay
        - _DEPRECATION_NOTICE
        - __IS_SMOOTH_SCROLLING
        - __scroll__direction
        - __CA_DELAYED_MODAL
        - _wq
        - __dataID__
        - _fbq
        - _hsq
        - _data
        - __REDUX_DEVTOOLS_EXTENSION__
