server:
  build: .
  volumes:
    - ./conf.js:/app/conf.js
    - ./extensions:/app/extensions
    - ./simulations:/app/simulations
  links:
    - mongodb
  command: [ "trade", "--paper" ]
  restart: always
  tty: true
  environment:
    - MONGODB_PORT_27017_TCP_ADDR=mongodb

mongodb:
  image: mongo:latest
  tty: true  
  volumes_from:
    - mongodb-data
  command: mongod --bind_ip_all --smallfiles
  # ports:
  #   - '27017:27017'
  #   - '27018:27018'
  #   - '27019:27019'
  #   - '28017:28017'

mongodb-data:
  image: mongo:latest
  volumes:
    - ./data/db:/data/db
  command: "true"

# Remove below comments to use this container. "adminMongo is a Web based user interface (GUI) to handle all your MongoDB connections/databases needs."
#
# adminmongo:
#  image: mrvautin/adminmongo
#  links:
#    - mongodb
#  tty: true
#  ports:
#    - "1234:1234"
#  environment:
#    - CONN_NAME=zenbot_mongodb
#    - DB_HOST=mongodb
#    - DB_PORT=27017
#  command: "npm start"
